OPRTNL/rbnb

app/controllers/bookings_controller.rb
app/controllers/cabins_controller.rb
app/models/cabin.rb
app/views/cabins/index.html.erb
app/views/cabins/show.html.erb
config/routes.rb
test/controllers/bookings_controller_test.rb

added show and index to cabin
+ corrected before action on cabin controller

added show and index to cabin

---

app/assets/stylesheets/pages/_home.scss
app/views/cabins/index.html.erb
app/views/layouts/application.html.erb
app/views/pages/home.html.erb

un peu de front pour le plaisir

homepage and cabins

---

app/controllers/bookings_controller.rb
app/models/user.rb
app/views/bookings/index.html.erb
app/views/shared/_navbar.html.erb
config/routes.rb

link booking navbar

---

app/views/shared/_navbar.html.erb

Add the view current_user profil and current_user edit profil in navbar

add edit profil link and profil view

---

app/controllers/cabins_controller.rb

Delete allbooked method in cabins controller

delete all_booked method in cabins controller

---

app/views/shared/_navbar.html.erb

Just add the place for the link with dropdown menu

add the become host place in navbar

---

app/controllers/bookings_controller.rb
app/controllers/cabins_controller.rb
app/models/booking.rb
app/views/cabins/show.html.erb

Added review's list in the cabin's show
Fixed booking logic

Booking dates

---

app/controllers/bookings_controller.rb
app/controllers/cabins_controller.rb
app/models/cabin.rb
app/views/cabins/_form.html.erb
app/views/shared/_navbar.html.erb
config/routes.rb

- routes change for cabins 
- change model cabin -rating- and update cabin new form
- add link create cabin in navbar and redirection to bookings after booked

Routes new cabin

---

app/views/users/show.html.erb

just add the basic html for the user show

add basic html for show user

---

app/assets/stylesheets/components/_about_us.scss
app/assets/stylesheets/components/_body.scss
app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_header.scss
app/assets/stylesheets/components/_index.scss
app/views/cabins/index.html.erb
app/views/layouts/application.html.erb
app/views/pages/home.html.erb

i love CSS

---

app/assets/stylesheets/components/_index.scss

add css import

---

app/assets/stylesheets/components/_user-card.scss
app/views/users/show.html.erb

customize show user

---

app/assets/stylesheets/components/_body.scss
app/assets/stylesheets/components/_featured_cabins.scss
app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_header.scss
app/assets/stylesheets/components/_index.scss
app/views/pages/home.html.erb

nous vaincrons le front

---

app/assets/stylesheets/components/_navbar.scss
app/views/shared/_navbar.html.erb

delete navbar dropdown list style and delete the message link

delete list style dropdown and delete message link

---

app/views/shared/_navbar.html.erb

add sign up when deconnect in navbar

add sign up to home when deconnnect

---

app/assets/stylesheets/components/_index.scss

add the scss file for login page

add and link to index scss file for login

---

app/assets/stylesheets/components/_log-in.scss
app/views/devise/sessions/new.html.erb

customize login page

---

app/assets/stylesheets/components/_banner_footer.scss
app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_call_action.scss
app/assets/stylesheets/components/_featured_cabins.scss
app/assets/stylesheets/components/_header.scss
app/views/pages/home.html.erb

footer ok
css ok sur home page

Homepage 3

---

app/views/devise/registrations/new.html.erb

customize sign up page

---

app/views/layouts/application.html.erb
app/views/pages/home.html.erb
app/views/shared/_footer.html.erb

add footer everywhere

---

app/views/devise/registrations/new.html.erb

customize more inputs sign up

---

app/assets/stylesheets/components/_index.scss
db/schema.rb

create scss file for create cabin

---

app/assets/stylesheets/components/_index.scss

scss create cabin

---

app/controllers/cabins_controller.rb
app/javascript/packs/application.js
app/javascript/plugins/init_mapbox.js
app/views/cabins/index.html.erb
app/views/layouts/application.html.erb
package.json
yarn.lock

added map feature in Cabins index
do not forget to : yarn add mapbox-gl + bundle + rails db:seed
before the rails s

added map feature in Cabins index

---

app/assets/stylesheets/components/_create-cabin.scss
app/views/cabins/_form.html.erb
app/views/layouts/application.html.erb

customize the create cabin page

---

app/assets/stylesheets/components/_index.scss

create scss file for bookings user page

---

app/assets/stylesheets/components/_bookings.scss
app/views/bookings/index.html.erb

customize bookings page for user

customize the booking page

---

app/assets/stylesheets/components/_bookings.scss
app/views/bookings/index.html.erb

change the class for li in booking page

---

app/controllers/cabins_controller.rb
db/schema.rb

fixed cabins

---

app/assets/stylesheets/components/_bookings.scss

cusotmize more bookings
